# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    - avoid_returning_null_for_future # https://dart-lang.github.io/linter/lints/avoid_returning_null_for_future.html
    - avoid_slow_async_io # https://dart-lang.github.io/linter/lints/avoid_slow_async_io.html
    - avoid_type_to_string # https://dart-lang.github.io/linter/lints/avoid_type_to_string.html
    - avoid_types_as_parameter_names # https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html
    - close_sinks # https://dart-lang.github.io/linter/lints/close_sinks.html
    - control_flow_in_finally # https://dart-lang.github.io/linter/lints/control_flow_in_finally.html
    - empty_statements # https://dart-lang.github.io/linter/lints/empty_statements.html
    - iterable_contains_unrelated_type # https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html
    - list_remove_unrelated_type # https://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html
    - literal_only_boolean_expressions # https://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html
    - no_duplicate_case_values # https://dart-lang.github.io/linter/lints/no_duplicate_case_values.html
    - no_logic_in_create_state # https://dart-lang.github.io/linter/lints/no_logic_in_create_state.html
    - prefer_void_to_null # https://dart-lang.github.io/linter/lints/prefer_void_to_null.html
    - unnecessary_statements # https://dart-lang.github.io/linter/lints/unnecessary_statements.html
    - unrelated_type_equality_checks # https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html
    - use_build_context_synchronously # https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html
    - always_declare_return_types # https://dart-lang.github.io/linter/lints/always_declare_return_types.html
    - always_put_required_named_parameters_first # https://dart-lang.github.io/linter/lints/always_put_required_named_parameters_first.html
    - avoid_field_initializers_in_const_classes # https://dart-lang.github.io/linter/lints/avoid_field_initializers_in_const_classes.html
    - prefer_const_constructors # https://dart-lang.github.io/linter/lints/prefer_const_constructors.html
    - camel_case_extensions # https://dart-lang.github.io/linter/lints/camel_case_extensions.html
    - camel_case_types # https://dart-lang.github.io/linter/lints/camel_case_types.html
    - cascade_invocations # https://dart-lang.github.io/linter/lints/cascade_invocations.html
    - empty_catches # https://dart-lang.github.io/linter/lints/empty_catches.html
    - constant_identifier_names # https://dart-lang.github.io/linter/lints/constant_identifier_names.html
    - curly_braces_in_flow_control_structures # https://dart-lang.github.io/linter/lints/curly_braces_in_flow_control_structures.html
    - eol_at_end_of_file # https://dart-lang.github.io/linter/lints/eol_at_end_of_file.html
    - file_names # https://dart-lang.github.io/linter/lints/file_names.html
    - join_return_with_assignment # https://dart-lang.github.io/linter/lints/join_return_with_assignment.html
    - leading_newlines_in_multiline_strings # https://dart-lang.github.io/linter/lints/leading_newlines_in_multiline_strings.html
    - library_names # https://dart-lang.github.io/linter/lints/library_names.html
    - library_prefixes # https://dart-lang.github.io/linter/lints/library_prefixes.html
    - noop_primitive_operations # https://dart-lang.github.io/linter/lints/noop_primitive_operations.html
    - null_closures # https://dart-lang.github.io/linter/lints/null_closures.html
    - omit_local_variable_types # https://dart-lang.github.io/linter/lints/omit_local_variable_types.html
    - one_member_abstracts # https://dart-lang.github.io/linter/lints/one_member_abstracts.html
    - only_throw_errors # https://dart-lang.github.io/linter/lints/only_throw_errors.html
    - package_prefixed_library_names # https://dart-lang.github.io/linter/lints/package_prefixed_library_names.html
    - prefer_collection_literals # https://dart-lang.github.io/linter/lints/prefer_collection_literals.html
    - prefer_conditional_assignment # https://dart-lang.github.io/linter/lints/prefer_conditional_assignment.html
    - prefer_const_constructors_in_immutables # https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html
    - prefer_const_literals_to_create_immutables # https://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html
    - prefer_const_declarations # https://dart-lang.github.io/linter/lints/prefer_const_declarations.html
    - prefer_constructors_over_static_methods # https://dart-lang.github.io/linter/lints/prefer_constructors_over_static_methods.html
    - prefer_equal_for_default_values # https://dart-lang.github.io/linter/lints/prefer_equal_for_default_values.html
    - prefer_expression_function_bodies # https://dart-lang.github.io/linter/lints/prefer_expression_function_bodies.html
    - prefer_final_fields # https://dart-lang.github.io/linter/lints/prefer_final_fields.html
    - prefer_final_in_for_each # https://dart-lang.github.io/linter/lints/prefer_final_in_for_each.html
    - prefer_final_locals  # https://dart-lang.github.io/linter/lints/prefer_final_locals.html
    - prefer_for_elements_to_map_fromIterable  # https://dart-lang.github.io/linter/lints/prefer_for_elements_to_map_fromIterable.html
    - prefer_foreach  # https://dart-lang.github.io/linter/lints/prefer_foreach.html
    - prefer_if_null_operators  # https://dart-lang.github.io/linter/lints/prefer_if_null_operators.html
    - prefer_if_elements_to_conditional_expressions  # https://dart-lang.github.io/linter/lints/prefer_if_elements_to_conditional_expressions.html
    - prefer_generic_function_type_aliases  # https://dart-lang.github.io/linter/lints/prefer_generic_function_type_aliases.html
    - prefer_function_declarations_over_variables  # https://dart-lang.github.io/linter/lints/prefer_function_declarations_over_variables.html
    - prefer_initializing_formals  # https://dart-lang.github.io/linter/lints/prefer_initializing_formals.html
    - prefer_inlined_adds  # https://dart-lang.github.io/linter/lints/prefer_inlined_adds.html
    - prefer_interpolation_to_compose_strings  # https://dart-lang.github.io/linter/lints/prefer_interpolation_to_compose_strings.html
    - prefer_is_empty  # https://dart-lang.github.io/linter/lints/prefer_is_empty.html
    - prefer_is_not_empty  # https://dart-lang.github.io/linter/lints/prefer_is_not_empty.html
    - prefer_iterable_whereType  # https://dart-lang.github.io/linter/lints/prefer_iterable_whereType.html
    - prefer_null_aware_method_calls  # https://dart-lang.github.io/linter/lints/prefer_null_aware_method_calls.html
    - prefer_relative_imports # https://dart-lang.github.io/linter/lints/prefer_relative_imports.html
    - prefer_spread_collections  # https://dart-lang.github.io/linter/lints/prefer_spread_collections.html
    - recursive_getters  # https://dart-lang.github.io/linter/lints/recursive_getters.html
    - prefer_typing_uninitialized_variables  # https://dart-lang.github.io/linter/lints/prefer_typing_uninitialized_variables.html
    - sized_box_for_whitespace  # https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html
    - type_annotate_public_apis  # https://dart-lang.github.io/linter/lints/type_annotate_public_apis.html
    - unnecessary_brace_in_string_interps  # https://dart-lang.github.io/linter/lints/unnecessary_brace_in_string_interps.html
    - unnecessary_const  # https://dart-lang.github.io/linter/lints/unnecessary_const.html
    - unnecessary_await_in_return  # https://dart-lang.github.io/linter/lints/unnecessary_await_in_return.html
    - use_named_constants  # https://dart-lang.github.io/linter/lints/use_named_constants.html
    - use_if_null_to_convert_nulls_to_bools  # https://dart-lang.github.io/linter/lints/use_if_null_to_convert_nulls_to_bools.html

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
